properties([
    parameters([
        string(
            name: 'execHost',
            defaultValue: '10.18.124.118',
            description: 'Execution host for SSH commands'
        ),
        string(
            name: 'sshUser',
            defaultValue: 'wlp',
            description: 'SSH username'
        )
    ])
])

pipeline {
    agent any

    stages {
        stage('Checkout Scripts') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/thewillyp/clearml_slurm_glue.git']]
                ])
            }
        }

        stage('Run Agent') {
            steps {
                sshagent(credentials: ['thewillyp-ssh-key']) {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-credentials',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        script {
                            sh """
                                ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${params.sshUser}@${params.execHost} '
                                    export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}";
                                    export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}";
                                    bash -s
                                ' < deploy_local/run_agent.sh
                            """
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'ClearML Docker agent started successfully!'
        }
        failure {
            echo 'Failed to start ClearML Docker agent.'
        }
        always {
            echo 'Pipeline completed.'
        }
    }
}
